### ISSUE TITLE
Google Ads + Firebase Analytics + OneSignal Build Fails

### ISSUE THREAD

**Issue by sourav-paul** [OneSignal/OneSignal-Unity-SDK#197] opened 2019-06-26 06:07 UTC
Can build till google ads and firebase analytics. But when imported onesignal build fails with error in console below:

stderr[
D8: Program type already present: android.support.customtabs.ICustomTabsService
FAILURE: Build failed with an exception.
*What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.

Environment:

- Unity 2018.4.2f1
- Windows 10
- Android Player 
- Scripting Runtime Version .Net 4.x 
- Scripting Backend IL2CPP 
- Api Compatibility Level .Net 4.x
- Google Ads Version 3.18.0
- Google Play Service Dependency Resolver Version 1.2.119
- Firebase Analytics Version 6.1.1
- OneSignal Unity SDK 2.7.9 (From May 8, 2019)

Steps to Reproduce Issue:

1. Set blank Unity project to as above configuration in project settings
2. Import Google Ads Plugin with everything in it
3. Resolve Dependency with force resolve
4. Import Firebase Analytics, only ignore Play Service Resolver
5. Put configuration .json file in the project
6. Resolve Dependency with force resolve
7. Build
8. Works with Ads and Analytics
9. Import Onesignal Unity SDK, exclude Play Service Resolver
10. Initialize OneSignal From Script.
11. Resolve Dependency with force resolve
12. Build
13. Fails with Error in console

**Comment by rgomezp** [comment] 2019-06-28 23:05
Hello,
This is a duplicate of #192 

Thanks for your response but will close this issue for consolidation

**Closed by rgomezp** 2019-06-28 23:05 UTC
