### ISSUE TITLE
Can't build with OneSignal + Admob

### ISSUE THREAD

**Issue by mubshar1** [OneSignal/OneSignal-Unity-SDK#193] opened 2019-06-20 14:45 UTC
![one](https://user-images.githubusercontent.com/45542019/59854818-0d0ae380-938d-11e9-8f5e-a5216fb9f7b5.PNG)

**Description:**

 build failed using the latest version of one signal and Admob.
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [:androidx.core.core-1.0.0:] AndroidManifest.xml:22:18-86
  	is also present at [:com.android.support.support-compat-28.0.0:] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:3-19:17 to override.

**Environment**

**Steps to Reproduce Issue:**

1. Import the latest OneSignalSDK.unitypackage and Admob into the project
  2. Resolve Dependencies 
  3. Attempt to build 
**Anything else:**

Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [:androidx.core.core-1.0.0:] AndroidManifest.xml:22:18-86
  	is also present at [:com.android.support.support-compat-28.0.0:] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:3-19:17 to override.

**Comment by rgomezp** [comment] 2019-06-25 20:40
Duplicate of #192

**Closed by rgomezp** 2019-06-25 20:40 UTC
