### ISSUE TITLE
[Android] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by elberto** [OneSignal/OneSignal-Unity-SDK#236] opened 2019-10-12 08:44 UTC
**Description:**
I updated to the latest SDK for my new app update. Did an Android resolve before build. Not having any issue on my test device on 8.0
Deployed on Google Play, now I'm having crash reports for about 5% of my users. Seems to happen only on devices below 8.0

**Environment**
1. One signal SDK Version 2.9.0
2. Unity 2019.2.14f1
3.Only on Android below 8.0 - Here are my crash stats.

Android 7.0 | 167 | 44,2 %
Android 7.1 | 92 | 24,3 %
Android 6.0 | 88 | 23,3 %
Android 5.1 | 28 | 7,4 %
Android 5.0 | 3 | 0,8 %

**Steps to Reproduce Issue:**

1. Can't manage to reproduce the issue, not having a 5-0 to 7.0 device
No ANR, just crash reports with the new update.

```
java.lang.NoClassDefFoundError: 
  at com.onesignal.NotificationRestoreService.onHandleIntent (NotificationRestoreService.java:49)
  at android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:66)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:158)
  at android.os.HandlerThread.run (HandlerThread.java:61)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:511)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:469)
```

**Comment by rgomezp** [comment] 2019-10-22 00:05
@gamediajustin Since there are other plugin in your project using AndroidX please follow this guide to enable Jetifier to solve the missing Java class errors.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Comment by rgomezp** [comment] 2019-10-22 00:06
Duplicate of #206

**Closed by rgomezp** 2019-10-22 00:06 UTC
