### ISSUE TITLE
dependencies collision with other SDK

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#196] opened 2019-06-26 04:14 UTC
Facebook SDK 7.16.1 (but I got this problem since 7.14)
gradle 3.2.1
latest android build tool
play service resolver 1.2.119

Build in unity cause this error

> D8: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior
> 
> FAILURE: Build failed with an exception.

I suspect that it might be a problem with just facebook. But maybe collision with other sdk might be a cause too

![image](https://user-images.githubusercontent.com/1042507/60150565-6e0a3f80-9803-11e9-8c54-98e3124849aa.png)

What could I do?

edit:

Have found this post https://stackoverflow.com/questions/49112190/

And it works. Now it just cannot register and received noti message. It just crash

edit2:

Now it work properly in android but it also require me to include firebase messaging package. It adding  `firebase-messaging:18.0.0` and `firebase-iid:[18.0.0]` in additional to your `firebase-messaging:[10.2.1, 12.1.0[`

**Comment by rgomezp** [comment] 2019-06-28 23:04
Hello,
Thank you for your response. Will close as this is a duplicate of #192

**Closed by rgomezp** 2019-06-28 23:04 UTC
