### ISSUE TITLE
Missing Android Support Library

### ISSUE THREAD

**Issue by Reconder** [OneSignal/OneSignal-Unity-SDK#321] opened 2020-10-05 13:48 UTC
**Description:**

Hello,

When I'm testing my app I get "Missing Android Support Library" error for my testing device on my app's all users page. It also doesn't receive any push notifications that I send.

**Environment**

1. I'm using Unity 2018.4.1f1 and Unity OneSignal SDK 2.13.1
1. I haven't implemented any other SDKs yet and my project is literally the sample scene that you get when you start a new project in Unity + empty object with OneSignal initialization script.
1. Android only.

**Steps to Reproduce Issue:**

1. Import the latest OneSignalSDK.unitypackage into your project
1. Initialize OneSignal with your app ID
1. Build a project and install the app on a test device
1. Attempt to receive a push notification

**Comment by nikomikulicic** [comment] 2020-10-07 15:06
I had the same issue in Unity 2019.2.1f1 and again in Unity 2019.4.1f1. Both times I resolved it with these instructions: https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility

However, I had Firebase SDK installed so I thought that was causing the problems. Maybe it was something else after all.

**Comment by rgomezp** [comment] 2020-11-13 22:57
Duplicate of #317 

Glad you were able to resolve.

**Closed by rgomezp** 2020-11-13 22:57 UTC
