### ISSUE TITLE
Unable to convert classes into dex format

### ISSUE THREAD

**Issue by VusalJalilov** [OneSignal/OneSignal-Unity-SDK#46] opened 2017-05-17 17:58 UTC
Tried multiple times. Followed the troubleshoot: https://documentation.onesignal.com/docs/troubleshooting-unity, but still cannot build in Unity 5.5.0f3.
`CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_131\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Android\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsCallback;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsClient;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsClient$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsIntent;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsIntent$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsIntent$Builder;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsService;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/customtabs/CustomTabsService$1;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
at com.android.dx.command.dexer.Main.run(Main.java:277)
at com.android.dx.command.dexer.Main.main(Main.java:245)
at com.android.dx.command.Main.main(Main.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
... 9 more
]
stdout[
processing archive D:\UnityProjects\HTF\Temp\StagingArea\android-libraries\GoogleAIDL\libs.\classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive D:\UnityProjects\HTF\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs.\unity-plugin-library.jar...
processing com/google/unity/ads/AdNetworkExtras.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/Banner$6.class...
processing com/google/unity/ads/Banner$7.class...
processing com/google/unity/ads/BuildConfig.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/NativeExpressAd.class...
processing com/google/unity/ads/NativeExpressAd$1.class...
processing com/google/unity/ads/NativeExpressAd$2.class...
processing com/google/unity/ads/NativeExpressAd$3.class...
processing com/google/unity/ads/NativeExpressAd$4.class...
processing com/google/unity/ads/NativeExpressAd$5.class...
processing com/google/unity/ads/NativeExpressAd$6.class...
processing com/google/unity/ads/NativeExpressAd$7.class...
processing com/google/unity/ads/NativeExpressAd$8.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityCustomNativeAdListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive D:\UnityProjects\HTF\Temp\StagingArea\android-libraries\GooglePlay\libs.\classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$Features.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing archive D:\UnityProjects\HTF\Temp\StagingArea\android-libraries\MainLibProj\libs.\play-games-plugin-support.jar...
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive D:\UnityProjects\HTF\Temp\StagingArea\android-libraries\animated-vector-drawable-23.4.0\libs.\classes.jar...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$1.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$AnimatedVectorDrawableCompatState.class...
processing android/support/graphics/drawable/AnimatedVectorDrawableCompat$AnimatedVectorDrawableDelegateState.class...
processing android/support/graphics/drawable/animated/BuildConfig.class...
processing archive D:\UnityProjects\HTF\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\libs.\classes.jar...
ignored resource .readme
processing android/support/v7/app/ActionBar.class...
processing android/support/v7/app/ActionBar$DisplayOptions.class...
processing android/support/v7/app/ActionBar$LayoutParams.class...
processing android/support/v7/app/ActionBar$NavigationMode.class...
processing android/support/v7/app/ActionBar$OnMenuVisibilityListener.class...
processing android/support/v7/app/ActionBar$OnNavigationListener.class...
processing android/support/v7/app/ActionBar$Tab.class...
processing android/support/v7/app/ActionBar$TabListener.class...
processing android/support/v7/app/ActionBarActivity.class...
processing android/support/v7/app/ActionBarDrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$1.class...
processing android/support/v7/app/ActionBarDrawerToggle$Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$DelegateProvider.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerArrowDrawableToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DummyDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$HoneycombDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$JellybeanMr2Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$ToolbarCompatDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb$SetIndicatorInfo.class...
processing android/support/v7/app/AlertController.class...
processing android/support/v7/app/AlertController$1.class...
processing android/support/v7/app/AlertController$2.class...
processing android/support/v7/app/AlertController$3.class...
processing android/support/v7/app/AlertController$4.class...
processing android/support/v7/app/AlertController$5.class...
processing android/support/v7/app/AlertController$AlertParams.class...
processing android/support/v7/app/AlertController$AlertParams$1.class...
processing android/support/v7/app/AlertController$AlertParams$2.class...
processing android/support/v7/app/AlertController$AlertParams$3.class...
processing android/support/v7/app/AlertController$AlertParams$4.class...
processing android/support/v7/app/AlertController$AlertParams$OnPrepareListViewListener.class...
processing android/support/v7/app/AlertController$ButtonHandler.class...
processing android/support/v7/app/AlertController$CheckedItemAdapter.class...
processing android/support/v7/app/AlertDialog.class...
processing android/support/v7/app/AlertDialog$Builder.class...
processing android/support/v7/app/AppCompatActivity.class...
processing android/support/v7/app/AppCompatCallback.class...
processing android/support/v7/app/AppCompatDelegate.class...
processing android/support/v7/app/AppCompatDelegate$NightMode.class...
processing android/support/v7/app/AppCompatDelegateImplBase.class...
processing android/support/v7/app/AppCompatDelegateImplBase$1.class...
processing android/support/v7/app/AppCompatDelegateImplBase$ActionBarDrawableToggleImpl.class...
processing android/support/v7/app/AppCompatDelegateImplBase$AppCompatWindowCallbackBase.class...
processing android/support/v7/app/AppCompatDelegateImplV11.class...
processing android/support/v7/app/AppCompatDelegateImplV14.class...
processing android/support/v7/app/AppCompatDelegateImplV14$AppCompatWindowCallbackV14.class...
processing android/support/v7/app/AppCompatDelegateImplV23.class...
processing android/support/v7/app/AppCompatDelegateImplV23$AppCompatWindowCallbackV23.class...
processing android/support/v7/app/AppCompatDelegateImplV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$2.class...
processing android/support/v7/app/AppCompatDelegateImplV7$3.class...
processing android/support/v7/app/AppCompatDelegateImplV7$4.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$6.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ListMenuDecorView.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDialog.class...
processing android/support/v7/app/AppCompatDialogFragment.class...
processing android/support/v7/app/AppCompatViewInflater.class...
processing android/support/v7/app/AppCompatViewInflater$DeclaredOnClickListener.class...
processing android/support/v7/app/NavItemSelectedListener.class...
processing android/support/v7/app/NotificationCompat.class...
processing android/support/v7/app/NotificationCompat$1.class...
processing android/support/v7/app/NotificationCompat$Builder.class...
processing android/support/v7/app/NotificationCompat$IceCreamSandwichExtender.class...
processing android/support/v7/app/NotificationCompat$JellybeanExtender.class...
processing android/support/v7/app/NotificationCompat$LollipopExtender.class...
processing android/support/v7/app/NotificationCompat$MediaStyle.class...
processing android/support/v7/app/NotificationCompatImpl21.class...
processing android/support/v7/app/NotificationCompatImplBase.class...
processing android/support/v7/app/ToolbarActionBar.class...
processing android/support/v7/app/ToolbarActionBar$1.class...
processing android/support/v7/app/ToolbarActionBar$2.class...
processing android/support/v7/app/ToolbarActionBar$ActionMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$MenuBuilderCallback.class...
processing android/support/v7/app/ToolbarActionBar$PanelMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$ToolbarCallbackWrapper.class...
processing android/support/v7/app/TwilightCalculator.class...
processing android/support/v7/app/Twili`

I do have the following enabled in my project: Unity Ads, Unity Analytics, Unity IAP, Google Mobile Ads, Google Play Games and Facebook SDK. I did remove support-v4 files from Facebook SDK long before importing OneSignal SDK.

Installed OneSignal SDK to a bare-bone new test project and could successfully build it. Unfortunately cannot build it in my current project and hardly able to identify the conflicting multiple java classes.

Any help would be appreciated.

**Comment by VusalJalilov** [comment] 2017-05-18 16:14
In order to reproduce the error:

1)	Create New Unity Project
2)	Enable Unity Ads
3)	Enable Unity Analytics
4)	Enable Unity IAP (import the SDK)
5)	Import Google Mobile Ads Unity Plugin v3.4.0 SDK
6)	Import play-games-plugin-for-unity v0.9.38a SDK
7)	Import Facebook SDK for Unity v7.9.4
8)	Import OneSignal SDK
9)	Build the apk.

**Comment by jkasten2** [comment] 2017-06-08 01:29
@VusalJalilov Thanks for the full log and reproduction steps. The following file will need to be deleted from your Unity project to fix the error you are getting.
`FacebookSDK/plugins/android/libs/customtabs-23.4.0.aar`

After this due to the number of Java methods in all these plugins you may see a `Too many field references to fit in one dex file` error.
![image](https://user-images.githubusercontent.com/645861/26908384-2fc594ce-4baf-11e7-899a-99596b853e70.png)

This means there are to many Java methods in all the libraries (and it's decencies) to build the app. We recommend following the suggestions in the thread below with some options on resolving this.
https://forum.unity3d.com/threads/multidex-support-on-android.325429/

**Comment by VusalJalilov** [comment] 2017-06-08 18:35
I have solved the issue by also deleting:
FacebookSDK/plugins/android/libs/support-vector-drawable-23.4.0.aar
FacebookSDK/plugins/android/libs/animated-vector-drawable-23.4.0.aar

**Comment by jkasten2** [comment] 2017-06-08 21:01
@VusalJalilov OneSignal shouldn't have any overlap with these libraries. Could share the exact error you were getting when you have those 2 files in your project?

**Comment by VusalJalilov** [comment] 2017-06-09 03:18
To make things clear.
I could successfully build my app without OneSignal SDK and with the below files in my Unity Project Assets folder:
FacebookSDK/plugins/android/libs/customtabs-23.4.0.aar
FacebookSDK/plugins/android/libs/support-vector-drawable-23.4.0.aar
FacebookSDK/plugins/android/libs/animated-vector-drawable-23.4.0.aar

Then I imported OneSignal SDK and removed only the customtabs-23.4.0.aar file and still could NOT build the apk. The full error log is attached.
[Console Error AFTER deleting customtabs-23.4.0.aar.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/1062929/Console.Error.AFTER.deleting.customtabs-23.4.0.aar.txt)

After removing 
FacebookSDK/plugins/android/libs/support-vector-drawable-23.4.0.aar
FacebookSDK/plugins/android/libs/animated-vector-drawable-23.4.0.aar
the build was successful.

**Comment by jkasten2** [comment] 2017-06-09 04:22
@VusalJalilov Great, thanks for all the details! Looks like removing those 2 .aar files was just enough for your APK to get under the 65K dex limit.

I recommend testing the facebook features in your app however just in case those Java classes are used by the options your using.

**Closed** 2017-06-09 04:22 UTC
