### ISSUE TITLE
[Bug]: Execution failed for task ':unityLibrary:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by golfacross** [OneSignal/OneSignal-Unity-SDK#573] opened 2022-12-21 11:06 UTC
### What happened?

I have installed the latest OneSignal version 3.0.8 from Scoped Registries. After installation I ran OneSignal SDK Setup without errors.

When I then try to build for my Android device I get this error:
CommandInvokationFailure: Gradle build failed. 

* What went wrong:
Execution failed for task ':unityLibrary:compileReleaseJavaWithJavac'.

Not sure how to solve this :-/

### Steps to reproduce?

```Markdown
1. Install OneSignal from Scoped Registries
2. build fro Android
```

### What did you expect to happen?

The app should build and everything should be fine.

### Unity version

2021.3.16f1 (latest)

### OneSignal Unity SDK version

3.0.8

### Platform

Android

### Relevant log output

```Shell
CommandInvokationFailure: Gradle build failed. 
/Applications/Unity/Hub/Editor/2021.3.16f1/PlaybackEngines/AndroidPlayer/OpenJDK/bin/java -classpath "/Applications/Unity/Hub/Editor/2021.3.16f1/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

Environment Variables:
BURST_ANDROID_MIN_API_LEVEL = 22
XPC_FLAGS = 0x0
JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF-8
MallocNanoZone = 0
ORIGINAL_XDG_CURRENT_DESKTOP = undefined
SHELL = /bin/zsh
SSH_AUTH_SOCK = /private/tmp/com.apple.launchd.z0sW2UrI0O/Listeners
HOME = /Users/jespermansa
PATH = /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

__CFBundleIdentifier = com.unity3d.unityhub
USER = jespermansa
__CF_USER_TEXT_ENCODING = 0x1F5:0x0:0x9
TMPDIR = /var/folders/kr/2715rkvj20q1pp3bxk02klfw0000gn/T/
LOGNAME = jespermansa
JAVA_HOME = /Applications/Unity/Hub/Editor/2021.3.16f1/PlaybackEngines/AndroidPlayer/OpenJDK
ANDROID_NDK_ROOT = /Applications/Unity/Hub/Editor/2021.3.16f1/PlaybackEngines/AndroidPlayer/NDK
XPC_SERVICE_NAME = application.com.unity3d.unityhub.32073928.32073935
COMMAND_MODE = unix2003


stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:30: error: cannot find symbol
public final class UnityIAMLifecycleHandler extends OSInAppMessageLifecycleHandler {
                                                    ^
  symbol: class OSInAppMessageLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:45: error: cannot find symbol
    public void onWillDisplayInAppMessage(OSInAppMessage message) {
                                          ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:51: error: cannot find symbol
    public void onDidDisplayInAppMessage(OSInAppMessage message) {
                                         ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:57: error: cannot find symbol
    public void onWillDismissInAppMessage(OSInAppMessage message) {
                                          ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:63: error: cannot find symbol
    public void onDidDismissInAppMessage(OSInAppMessage message) {
                                         ^
  symbol:   class OSInAppMessage
  location: class UnityIAMLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:38: error: cannot find symbol
        void onWillDisplayInAppMessage(OSInAppMessage message);
                                       ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:39: error: cannot find symbol
        void onDidDisplayInAppMessage(OSInAppMessage message);
                                      ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:40: error: cannot find symbol
        void onWillDismissInAppMessage(OSInAppMessage message);
                                       ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:41: error: cannot find symbol
        void onDidDismissInAppMessage(OSInAppMessage message);
                                      ^
  symbol:   class OSInAppMessage
  location: interface WrapperLifecycleHandler
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:44: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:50: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:56: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/onesignal/UnityIAMLifecycleHandler.java:62: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/jespermansa/Numfeud2023b/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
]
stdout[

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jp-gmr** [comment] 2022-12-21 19:39
Additional info on this: it seems that android dependencies for the latest release got broken recently. We made a "Resolve" of dependencies in the project last week, and it got one signal 4.8.3 libraries in the Plugins/Android folder. But now, without doing any change in the project manifest, the same "Resolve" of android ependencies is fetching "com.onesignal.xxxxxx-5.0.0-alpha1-test" files, and the build is getting broken as reported in this ticket.

**Comment by shefich** [comment] 2022-12-21 20:14
@jp-gmr what changes should we do in project manifest?
I made builds for several projects successfully, but one project has these errors upon build.

**Comment by jp-gmr** [comment] 2022-12-21 22:41
No changes in the project, just forcing the resolution of android libraries in External Dependencies Manager brings up these "alpha-test" libraries, and then the build fails.
In our case, we do not resolve libraries on build stage, but do that manually when changing any native 3rd party plugin. Doing that step this week, got wrong dependencies. Rolling back to the previous manifest settings, i.e, identical to what we had before (including One Signal 3.0.7) still brought the broken android libraries.
Our guess is that something in the cloud repositories got configured, so resolving libraries in the last couple of days is fetching libraries that are not supposed to be included. So the "bug" is not in the code, but in the cloud repository config files.

**Comment by shefich** [comment] 2022-12-21 22:56
so we should wait for the "cloud update" ? we can't have a fix until you will update some libraries in the cloud?

**Comment by jp-gmr** [comment] 2022-12-22 00:47
That really depends on the OneSignal dev team, which I am not part of. I am a OneSignal SDK user, developing a mobile app. And had the same bug as reported by the OP.

**Comment by vvlad1pp** [comment] 2022-12-22 02:09
+

**Comment by jkasten2** [comment] 2022-12-22 04:58
I attempted to reproduce the issue with OneSignal Unity SDK 3.0.8 and it is correctly pulling in the `com.onesignal.OneSignal-4.8.3` when testing on Unity 2021.3.16f1 on a new project.

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/645861/209059642-c3e18440-8fe1-477d-bcd3-94aad64eb3b2.png">

Can you check what version of OneSignal you have in `Assets/Plugins/Android`? As well as `ProjectSettings/AndroidResolverDependencies.xml`?

Also `GvhProjectSettings.xml` may have an effect on what versions of libraries are pulled in, so sharing the settings here from `ProjectSettings/GvhProjectSettings.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<projectSettings>
  <projectSetting name="Google.IOSResolver.VerboseLoggingEnabled" value="False" />
  <projectSetting name="Google.PackageManagerResolver.VerboseLoggingEnabled" value="False" />
  <projectSetting name="Google.VersionHandler.VerboseLoggingEnabled" value="False" />
  <projectSetting name="GooglePlayServices.PromptBeforeAutoResolution" value="False" />
  <projectSetting name="GooglePlayServices.UseJetifier" value="True" />
</projectSettings>
```

**Comment by Heartkage** [comment] 2022-12-22 09:20
Same here
When External Dependency Resolver resolves all dependencies in project, it updates OneSignal's aar. to 5.0.0-alpha1-test. Then everything breaks
![image](https://user-images.githubusercontent.com/32365063/209101223-58e1915f-955c-4375-baa0-d5cd9f0629a7.png)

**Comment by golfacross** [comment] 2022-12-22 11:01
I am also seeing the alpha1-test, both in plugins/android and in the AndroidResolverDependencies.xml:

<file>Assets/Plugins/Android/com.onesignal.core-5.0.0-alpha1-test.aar</file>
    <file>Assets/Plugins/Android/com.onesignal.in-app-messages-5.0.0-alpha1-test.aar</file>
    <file>Assets/Plugins/Android/com.onesignal.location-5.0.0-alpha1-test.aar</file>
    <file>Assets/Plugins/Android/com.onesignal.notifications-5.0.0-alpha1-test.aar</file>
    <file>Assets/Plugins/Android/com.onesignal.OneSignal-5.0.0-alpha1-test.aar</file>
    
    How to change this?

**Comment by jkasten2** [comment] 2022-12-22 16:44
> This occurs when we added any 3rd-party dependency and it starts resolve all dependencies by External Dependency Resolver. When it resolves all dependencies in project, it updates OneSignal's aar to 5.0.0-alpha1-test.

Thanks @Heartkage, this was key to reproducing the issue. I was able to reproduce with another library that also uses EDM4U, FirebaseAuth.

## Issue
The root of the issue is [EDM4U (External Dependency Manager for Unity)](https://github.com/googlesamples/unity-jar-resolver) is very aggressive with updating Android packages to attempt to find a matching set of transitive dependencies. Even bumping major versions which is in this case is going from OneSignal 4.x.x to 5.x.x. OneSignal recently published a 5.x.x nightly vision of the `com.onesignal:OneSignal` library which uncovered this version locking issue.

## Workaround
Modify the local copy of the OneSIgnal Unity Android to lock the `com.onesignal:OneSignal` Android dependency version.  To do this follow these steps:
1. In your project directory, copy `Library/PackageCache/com.onesignal.unity.android@x.x.x` and paste it into the `Packages` folder.
* x.x.x = the version of the OneSignal Unity version you are using.
3. Open `Packages/com.onesignal.unity.android@x.x.x/Editor/OneSignalAndroidDependencies.xml`
4. Add `[]` around the version number in this file and save it.
* example: `<androidPackage spec="com.onesignal:OneSignal:[4.8.3]" />`
5. Unity may pick up the change, if not you can run `Assets` > `External Dependency Manager` > `Android Resolver` > `Force Resolve`.

## Fix
OneSignal will ship a new Unity SDK to lock the version as noted above so you won't have to continue to manually doing so.

**Comment by shefich** [comment] 2022-12-22 17:35
It works, thank you.

**Closed** 2022-12-22 18:35 UTC

**Comment by jkasten2** [comment] 2022-12-22 19:14
This is now fixed in [OneSignal Unity SDK 3.0.9](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.9).

**Comment by jp-gmr** [comment] 2022-12-22 19:35
Awesome! thanks a lot for the quick turnaround!

**Comment by DanielZ15** [comment] 2023-01-13 13:46
Just ran into this issue and wanted to say a BIG THANK YOU for the fix!
