### ISSUE TITLE
NullReferenceException: OneSignal.isValidSuccessFailureDelegate

### ISSUE THREAD

**Issue by jackatfp** [OneSignal/OneSignal-Unity-SDK#300] opened 2020-05-21 11:46 UTC
**Description:**

We start having this issue after upgrade to the latest version. According to Crashlytics, it affects more than 3k users every day

**Environment**

1. What version of the Unity OneSignal SDK are you using?
**2.12.2 Release**
1. Does the issue occur only in iOS, Android, etc?
**Andriod Only**

**Anything else:**

Non-fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at OneSignal.isValidSuccessFailureDelegate(OneSignal)
       at OneSignal.onPostNotificationFailed(OneSignal)

**Comment by Khaled-Wolf** [comment] 2020-06-02 07:49
I have the same issue

**Comment by rgomezp** [comment] 2020-08-05 00:18
Howdy,
Thank you for your patience. Are you still seeing this issue @Khaled-Wolf @jackatfp ?

**Comment by Arrnav** [comment] 2020-08-23 17:07
I'm facing the same problem. Is there no fix to this? It is urgent for a client project.

**Comment by Khaled-Wolf** [comment] 2020-08-27 19:33
Hello @rgomezp 
Yes but we've applied the following check to prevent this error:
![image](https://user-images.githubusercontent.com/65023622/91486623-3a1e2480-e8b5-11ea-8cb9-54faf88eee08.png)

**Comment by shefich** [comment] 2021-09-23 16:01
Still have this issue on the version 2.14.3 installed from unity's package manager.
Tried to fix by changing lines from OneSignal.cs to these ones:
"if (jsonObject==null || !isValidDelegate(jsonObject) || !jsonObject.ContainsKey("delegate_id"))"
but nothing changed maybe because now this file is controlled by package manager.
Changes requested!

**Comment by shefich** [comment] 2021-10-13 18:16
Ok, I made a "controlled" crash and get logs:
As far as I see the problem is with the empty "delegate_id" inside the jsonObject which goes to isValidSuccessFailureDelegate boolean.
Inside the isValidSuccessFailureDelegate there is a check: isValidDelegate(jsonObject). But in this check: jsonObject.ContainsKey("delegate_id"). It is really there, but it is empty. So it goes to NullReferenceException here:
"if (!delegateId.ContainsKey("success") || !delegateId.ContainsKey("failure"))"

**Comment by shefich** [comment] 2022-03-25 16:38
@rgomezp we need the fix as 2 years almost passed!

**Comment by jkasten2** [comment] 2022-03-25 20:46
I reviewed the stack trace noted in this issue and can report the code has been overhauled in the [OneSignal-Unity-SDK 3.0.0 release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.0) and this should no longer be an issue. Follow the [OneSignal Step-by-Step Unity 2.x to 3.0.0 Upgrade Guide](https://documentation.onesignal.com/docs/step-by-step-unity-2x-to-300-update-guide) to get up and running quickly with this version.

@shefich @Arrnav @Khaled-Wolf @jackatfp If you can provide steps to reproduce we can attempt to reproduce to ensure the exact scenario is indeed fixed.

**Comment by shefich** [comment] 2022-03-25 20:53
@jkasten2 thank you for your answer, but I am talking about 2.x versions, as this topic mentions this version in the decription.
I don't want to switch to the 3.xx version as it has beta status, so nobody guarantees its work in the release projects.

**Comment by jkasten2** [comment] 2022-03-25 21:04
@shefich It was just released out of beta on the 23rd. It is available via currently via the Unity Package Manager, and will soon be available from the Unity Asset Store.

**Comment by shefich** [comment] 2022-03-25 21:27
@jkasten2 oh sorry, I can see it now. I will update the package and will let you know if the issue still exist.

**Comment by jkasten2** [comment] 2022-04-23 02:30
Closing this issue as resolved, the 3.0.0 release addressed this issue. The [3.0.1 release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.1) is [now available on the Unity Asset Store](https://assetstore.unity.com/packages/add-ons/services/billing/onesignal-sdk-193316).

If you continue to see similar issues on 3.x.x please create a [new issue](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/new/choose) and we can follow up.

**Closed by jkasten2** 2022-04-23 02:30 UTC
Labels: Possible Bug
