### ISSUE TITLE
[Bug]: You can't publish an iOS app in the app store with one signal

### ISSUE THREAD

**Issue by joaquingrech** [OneSignal/OneSignal-Unity-SDK#500] opened 2022-05-06 03:18 UTC
### What happened?

It will compile but it will fail to publish with this error from the store.
Invalid Bundle. The bundle at 'DogfightElite.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed file 'Frameworks'. With error code STATE_ERROR.VALIDATION_ERROR.90206 for id 18659c81-ca15-4c5f-8f76-7bfe1a6bec60

### Steps to reproduce?

```Markdown
Build in Xcode and try to publish to the app store the app
```

### What did you expect to happen?

it should publish

### Unity version

2021.3.1

### OneSignal Unity SDK version

3.0.1

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment] 2022-05-06 04:26
@joaquingrech Thanks for reporting! I was able to reproduce a similar error when use the "Distribute App" option after running Archive. However it was with `UnityFramework.framework` and not OneSignal oddly enough:


![image](https://user-images.githubusercontent.com/645861/167066289-44a8b863-9a92-42b0-b28e-7c921602b37f.png)

```
Prepared archive for uploading
Upload failed
	error: App Store Connect Operation Error
Invalid Bundle. The bundle at 'OneSignalExample.app/Frameworks/UnityFramework.framework' contains disallowed file 'Frameworks'. With error code STATE_ERROR.VALIDATION_ERROR.90206 for id e1caea1c-dfc5-4c4e-9874-76f3966f4bf3
```

I was testing with Unity 2020.3.33f1 and Xcode 13.3.1.

I am getting the same error type of `STATE_ERROR.VALIDATION_ERROR.90206`, however not sure if I am running into the same root issue as you. Either way since I can reproduce the same error type we will dig into this as there is a good chance what we learn here would result finding a solution for the OneSignal framework as well.

**Comment by jkasten2** [comment] 2022-05-06 05:59
## Root Issue
The `STATE_ERROR.VALIDATION_ERROR.90206` error happens if `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is not configured correctly. This should be set to `Yes` ONLY on the main target `Unity-iPhone`.

## Step-by-Step to fix
1. In Xcode select the `Unity-iPhone` project on the far left, under TARGETS select `Unity-iPhone`.
2. Go to the "Build Settings" tab, search for `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` here.
3. Set this to `Yes`.
<img width="841" alt="image" src="https://user-images.githubusercontent.com/645861/167074156-533a7a74-ff08-4d8a-a43e-c2a484dfc595.png">
4. Go through each target and make sure it is `No` for all others.
<img width="825" alt="image" src="https://user-images.githubusercontent.com/645861/167074606-d9b4fbd5-6da2-42be-8689-adaec28783bf.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/645861/167074631-2365cc2e-3ba1-4b15-bab7-b24f55de4cb0.png">

## How it gets set
Still investigating why `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` would not be the correct value. For me `UnityFramework` was incorrectly set `Yes` and `Unity-iPhone` was incorrectly set to `No`.
There is a PR on EDM4U https://github.com/googlesamples/unity-jar-resolver/pull/508, that is included in 1.2.170 and released on Apr 4, 2022 that may fix this wrong values automatically. Will update this comment once I confirm.

### Reproducing the OPs exact error
`OneSignalNotificationServiceExtension` was correctly set to `No`, however when I changed this to `Yes` and was able to reproduce the OPs exact error. However I am not able to reproduce it being set to `Yes` by default.

**Comment by joaquingrech** [comment] 2022-05-06 15:04
no way to set all this up on a script automatically? Otherwise this is going to be a mess for everyone that updates to 3.0.1

**Comment by jkasten2** [comment] 2022-05-06 20:10
@joaquingrech We have found a fix for this, it will be included in the next release.

**Closed by jkasten2** 2022-05-06 20:10 UTC

**Comment by Xenkill** [comment] 2023-11-09 20:25
For the ones that still need a solution for unity 2022.X.  Pushing the IOS minimum version over 12.5 seem to do the trick. No more STATE_ERROR.VALIDATION_ERROR.90206.

So, inside the project settings of unity [Edit -> Project Settings...]
In the field: "Target Minimum iOS Version", set it to "12.5".

Build you IPA, and you should be able to push it to apple connect without any errors.
