### ISSUE TITLE
FATAL EXCEPTION [firebase-iid-executor]

### ISSUE THREAD

**Issue by saeed042** [OneSignal/OneSignal-Unity-SDK#271] opened 2020-02-06 07:43 UTC
**Description:**
 A lot of Crashes reported on Google Console.

Unity version : 2018.4.15f1
**Environment**

1. Unity OneSignal SDK 2.9.0
2. implementation 'com.android.support:cardview-v7:[26.0.0, 27.2.0[' // 
    implementation 'com.android.support:customtabs:[26.0.0, 27.2.0[' // 
    implementation 'com.android.support:support-v4:[26.0.0, 27.2.0[' // 
    implementation 'com.google.ads.mediation:facebook:5.6.0.0' // 
    implementation 'com.google.ads.mediation:ironsource:6.10.0.0' // 
    implementation 'com.google.ads.mediation:unity:3.3.0.0' // 
    implementation 'com.google.android.gms:play-services-ads:18.3.0' // 
    implementation 'com.google.android.gms:play-services-base:[10.2.1, 12.1.0[' // 
    implementation 'com.google.android.gms:play-services-location:[10.2.1, 12.1.0[' // 
    implementation 'com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[' // 
3. Android
 

java.lang.Error: FATAL EXCEPTION [firebase-iid-executor] Unity version : 2018.4.15f1 Device model : OPPO CPH1803 Device fingerprint: OPPO/CPH1803/CPH1803:8.1.0/OPM1.171019.026/1577201295:user/release-keys Caused by at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
at com.google.firebase.iid.FirebaseInstanceId.getInstance (Unknown Source:1)
at com.google.firebase.iid.zzaw.zzg (Unknown Source:52)
at com.google.firebase.iid.FirebaseInstanceId.zzi (Unknown Source:60)
at com.google.firebase.iid.FirebaseInstanceId.zza (Unknown Source:147)
at com.google.firebase.iid.zzn.run (Unknown Source:10)
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
at java.lang.Thread.run (Thread.java:764)

![Capture1](https://user-images.githubusercontent.com/56425079/73915921-25a91900-48de-11ea-83cf-5a4118a2447e.PNG)

**Comment by Jyjoo** [comment] 2020-02-07 10:28
We have the same error here. Anyone find a solution ?

**Comment by rgomezp** [comment] 2020-02-11 00:05
Hello,
What are the reproduction steps?

**Comment by saeed042** [comment] 2020-02-11 04:42
@rgomezp I have collected these crashes from Console.

**Comment by smumair06** [comment] 2020-02-11 09:07
I also got report on Google Play store for same crash, don't have steps for reproduction :( though.

![Screenshot 2020-02-11 at 2 05 02 PM](https://user-images.githubusercontent.com/17721181/74223057-b36a7700-4cd7-11ea-9fc2-ad3b23f2ee0e.png)

Device reported the issue is Samsung Galaxy A10.

**Comment by saeed042** [comment] 2020-02-11 12:18
My issue has been solved by adding following code in mainTemplate.gradle file
classpath 'com.google.gms:google-services:4.2.0'  ( just after this  line of code "classpath 'com.android.tools.build:gradle.........")

**Comment by jkasten2** [comment] 2020-02-24 02:23
@saeed042 Good to hear this was able to solve your issue. This specific crash may be related to a set of specific plugins in your class the problem may not have affected everyone. Closing this issue as resolved.

**Closed by jkasten2** 2020-02-24 02:23 UTC
Labels: Help Wanted, Need More Information
