### ISSUE TITLE
Conflict of OneSignal 2.4.1 with Google Play Games Plugin 0.9.42

### ISSUE THREAD

**Issue by DimHoly** [OneSignal/OneSignal-Unity-SDK#75] opened 2017-11-28 13:59 UTC
Hello everybody.

I am trying to integrate OneSignal 2.4.1 SDK in my project that implements the Google Play Game Services (version 0.9.42)

Using only the Google Play Games plugin i can normally login to the services in my android game. When i integrate OneSignal it crashes when i try to login. 

Keep in mind that when i import OneSignal SDK i get the following Warning message in Unity console:

> Found conflicting Android library gpgs-plugin-support
> 
> Assets/Plugins/Android/gpgs-plugin-support-0.9.42 (managed by the Android Resolver) conflicts with:
> Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.42/gpgs-plugin-support-0.9.42.aar
> 
> Your application is unlikely to build in the current state.
> 
> To resolve this problem you can try one of the following:
> * Updating the dependencies managed by the Android Resolver
>   to remove references to old libraries.  Be careful to not
>   include conflicting versions of Google Play services.
> * Contacting the plugin vendor(s) with conflicting
>   dependencies and asking them to update their plugin.
> 
> UnityEngine.Debug:LogWarning(Object)
> Google.Logger:Log(String, LogLevel)
> GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
> GooglePlayServices.ResolverVer1_1:FindAndResolveConflicts()
> GooglePlayServices.<DoResolution>c__AnonStorey17:<>m__29()
> GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__26(List`1)
> GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
> GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
> GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

I used the Android Resolver (both the 'Resolve' and 'Force Resolve' options) but still my app crashes when i try to log-in to google play services.

Any ideas on how to fix the above issue?

Thank you

**Comment by Zorcher** [comment] 2017-12-09 00:56
Able to reproduce.

Specific error message I am getting:

W/dalvikvm( 6213): threadid=1: thread exiting with uncaught exception (group=0x40e33ae0)
E/AndroidRuntime( 6213): FATAL EXCEPTION: main
E/AndroidRuntime( 6213): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime( 6213): Caused by: java.lang.NoClassDefFoundError: android.arch.core.internal.FastSafeIterableMap

**Comment by Darkdevil79** [comment] 2017-12-31 10:32
Any news on a fix

**Comment by BlueSpiritbox** [comment] 2018-02-11 00:16
I'm having this issue as well. I'm using OneSignal 2.5.0 and Play Services 0.9.50. Tried the Android Resolver, but no luck.

**Comment by BlueSpiritbox** [comment] 2018-02-11 01:38
I got it to work :) I was able to fix this issue by going in the OneSignalEditorScript.cs file and change the following lines

>private static readonly string PLAY_SERVICES_VERSION = "+";
>private static readonly string ANDROID_SUPPORT_VERSION = "+";

to

>private static readonly string PLAY_SERVICES_VERSION = "**10**+";
>private static readonly string ANDROID_SUPPORT_VERSION = "**25**+";

It's actually a solution that they suggested for a build error with Facebook SDK https://documentation.onesignal.com/docs/troubleshooting-unity#section-build-error-with-facebook-sdk.
It seems to work for the Google Play Games plug as well. Tested it on an Android device, and I'm able to log into Play Games and use the OneSignal messaging without any problems.

**Comment by iamAloTheGreat** [comment] 2018-03-14 12:41
Hi @BlueSpiritbox. Can you tell us what is your SDK version? and other information coz I tried this solution also but still unable to build for android. Thanks.

**Comment by BlueSpiritbox** [comment] 2018-03-14 12:51
@iamAloTheGreat I'm using OneSignal 2.5.0 and Google Play Games Plugin 0.9.50, and running it on Unity 2017.3.0f3

**Comment by iamAloTheGreat** [comment] 2018-03-14 13:28
Hi I tried to create an empty project and imported PlayGames 0.9.50 and OneSignal 2.5.0, but I'm still unable to build. Should I update my Play Services Resolver?

**Comment by BlueSpiritbox** [comment] 2018-03-14 13:32
@iamAloTheGreat Yeah, give that a try. I'm using Play Services Resolver 1.2.61.0 by the way.

**Comment by iamAloTheGreat** [comment] 2018-03-14 14:01
Still not working.. what Android SDK version do you have for building?

**Comment by BlueSpiritbox** [comment] 2018-03-14 14:57
@iamAloTheGreat tried it with Android SDK 25 and 26, and both worked fine.

**Comment by iamAloTheGreat** [comment] 2018-03-15 06:33
Thanks for replying @BlueSpiritbox 
I tried it but still no luck. I have an error CommandInvokationFailure: Failed to re-package resources.
/Users/aloimmaculata/android-sdk-macosx/build-tools/27.0.3/aapt package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I
I downloaded the latest sdk

**Comment by Nightsd01** [comment] 2018-03-26 19:05
@iamAloTheGreat Is this issue still occurring in the latest version (2.6.3) of the OneSignal SDK?

**Comment by iamAloTheGreat** [comment] 2018-03-28 09:33
Yes @Nightsd01 , I tried the latest version as v2.6.3.

**Comment by jkasten2** [comment] 2018-03-28 10:44
@iamAloTheGreat I am not able to reproduce the `Failed to re-package resources.` error you are seeing with a new Unity project with [OneSignal 2.6.4](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.6.4) and Google Play Games Plugin 0.9.50. We did change the Google Play services and Android Support library dependencies from `+` to a version range. Can you try again with  our 2.6.4 version?

One other thing to note is with these 2 plugins added to your project together will put you over the 65k dex limit. You will see something like this if this is the case.
```
CommandInvokationFailure: Unable to convert classes into dex format.
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/josh/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[

trouble writing output: Too many field references to fit in one dex file: 81429; max is 65536.
You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.
References by package:
```

To fix you will need to set the "Build System" to Gradle.
![image](https://user-images.githubusercontent.com/645861/38024508-15525aa6-323a-11e8-9e7c-ac70b6aa71ec.png)


If you are still seeing issues after trying this please attach your full editor log so we can help debug the issue.
https://docs.unity3d.com/Manual/LogFiles.html

**Comment by jkasten2** [comment] 2018-04-07 22:53
@DimHoly I believe the original app crash you reported is no longer an issue with the latest versions I noted above so closing this issue

**Closed by jkasten2** 2018-04-07 22:53 UTC
Labels: bug
