### ISSUE TITLE
[FATAL EXCEPTION - 2.8.2] many crash report com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob

### ISSUE THREAD

**Issue by nhnpro** [OneSignal/OneSignal-Unity-SDK#211] opened 2019-08-16 09:48 UTC
Recently we meet many exceptions when upgrade OnesignalSDK Unity 2.8.2:
-  Unity version     : 2018.4.6f1

java.lang.Error: FATAL EXCEPTION [FocusHandlerThread]
Unity version     : 2018.4.6f1
Device model      : LAVA iris88
Device fingerprint: LAVA/iris88/iris88:8.1.0/O11019/1528898807:user/release-keys
Caused by
  at android.os.Parcel.readException (Parcel.java:2009)
  at android.os.Parcel.readException (Parcel.java:1951)
  at android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:180)
  at android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:44)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob (OneSignalSyncServiceUtils.java:148)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:116)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:63)
  at com.onesignal.OneSignal.onAppLostFocus (OneSignal.java:1155)
  at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run (ActivityLifecycleHandler.java:257)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.os.HandlerThread.run (HandlerThread.java:65)

**Comment by rgomezp** [comment] 2019-08-21 23:09
Duplicate of https://github.com/OneSignal/OneSignal-Unity-SDK/issues/191

**Closed by rgomezp** 2019-08-21 23:09 UTC
