### ISSUE TITLE
Is it possible to edit segments via REST API?

### ISSUE THREAD

**Issue by DmytroSobko** [OneSignal/OneSignal-Unity-SDK#318] opened 2020-09-18 09:41 UTC
Is it possible to edit segments via REST API?

I see only "Create Segments" and "Delete Segments" here
https://documentation.onesignal.com/reference/create-segments

**Comment by jkasten2** [comment] 2021-02-08 07:00
There is not today, we will consider adding it in the future to the REST API.
*Reference: Duplicate of: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1154*

**Closed by jkasten2** 2021-02-08 07:00 UTC
