### ISSUE TITLE
Not Compatible with latest admob+google playservices

### ISSUE THREAD

**Issue by Zeeshananwar077** [OneSignal/OneSignal-Unity-SDK#195] opened 2019-06-24 05:12 UTC
**Description:**

CommandInvokationFailure: Failed to re-package resources.
E:\sdk\build-tools\28.0.3\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "E:/sdk\platforms\android-29\android.jar" -F bin/resources.ap_ --extra-packages android.arch.lifecycle:androidx.arch.core:androidx.asynclayoutinflater:androidx.coordinatorlayout:androidx.core:androidx.cursoradapter:androidx.customview:androidx.documentfile:androidx.drawerlayout:androidx.fragment:androidx.interpolator:androidx.legacy.coreui:androidx.legacy.coreutils:androidx.lifecycle.livedata:androidx.lifecycle.livedata.core:androidx.lifecycle:androidx.lifecycle.viewmodel:androidx.loader:androidx.localbroadcastmanager:androidx.print:androidx.slidingpanelayout:androidx.swiperefreshlayout:androidx.versionedparcelable:androidx.viewpager:android.support.customtabs:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:com.google.android.gms.ads.impl:com.google.android.gms.ads_base:com.google.android.gms.ads_identifier:com.google.android.gms.ads:com.google.android.gms.auth.api:com.google.android.gms.auth.api.phone:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.common:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.gass:com.google.android.gms.location:com.google.android.gms.measurement_base:com.google.android.gms.measurement.sdk.api:com.google.android.gms.nearby:com.google.android.gms.places_placereport:com.google.android.gms.stats:com.google.android.gms.tasks:com.google.firebase:com.google.firebase.iid:com.google.firebase.iid.internal:com.google.firebase.analytics.connector:com.google.firebase.messaging:com.google.games.bridge:com.unity.purchasing:com.android.vending.billing:com.google.unity.ads:com.unity.purchasing.googleplay:com.google.example.games.mainlibproj:com.onesignal:com.onesignal.onesignalsdk:com.unity3d.ads -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\android.arch.lifecycle.runtime-1.1.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.coordinatorlayout.coordinatorlayout-1.0.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-fragment-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-v4-27.1.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-ads-17.2.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-ads-lite-17.2.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-auth-16.0.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-base-17.0.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-basement-17.0.0\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.firebase.firebase-messaging-19.0.1\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.google.games.gpgs-plugin-support-0.9.64\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\common\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\GoogleAIDL\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\GooglePlay\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\onesignal-unity\res" -S "D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\OneSignalConfig\res"

stderr[
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_page.xml:15: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_page.xml:15: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <TextView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_page.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/browser_actions_context_menu_page for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml:5: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml:5: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/browser_actions_context_menu_row for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_action.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_action.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_action.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/notification_action for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_action_tombstone.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_action_tombstone.xml:37: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_action_tombstone.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/notification_action_tombstone for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/notification_template_big_media for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:89: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:56: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/notification_template_big_media_custom for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/notification_template_big_media_narrow for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:107: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:93: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:93: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:59: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:49: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:49: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml: note: using v17 attributes; synthesizing resource com.ultron.badminton3D.tennis3D:layout/notification_template_big_media_narrow_custom for configuration v17.
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_template_custom_big.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout\notification_template_custom_big.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <FrameLayout>
D:\NewPlugin2018.3.14\Temp\StagingArea\android-libraries\androidx.core.core-1.0.0\res\layout-v16\notification_template_custom_big.xml:103: n<message truncated>

**Environment**

1. - unity 2018.3.14
2. - Playservices GooglePlayGamesPlugin-0.9.61
3. - GoogleMobileAds-v3.17.0
4. - OneSignal-Unity-SDK-2.7.9
5. - Sdk Updated to api 29
6. -Build System Internal
7. -Using 3.5 .net
8. -Exporting for ARM x86 only

with these 3 plugin in my project when ever i try to resolve it gives me resolution successful but when i go for build project its gives me error, what so ever play services resolver version i use it gets me Resolution succeed but fails on build.

**Comment by SamiUllah42** [comment] 2019-06-24 08:10
Struggling with same issue . using unity 2018.3.0 , tried different versions of admob +onsignal . 
build Gradle , Armv7 and 64 . nothing is working for me even after updating Android Sdk and using embedded and external jdk. only 2 packages in my project Onesignal and Admob.

want to recreate issue
import admob 
import onsignal
resolve dependencies
Build project it wont  work .

**Comment by rgomezp** [comment] 2019-06-25 20:40
Duplicate of #192

**Closed by rgomezp** 2019-06-25 20:40 UTC
