### ISSUE TITLE
[Bug]: Build Error

### ISSUE THREAD

**Issue by hardipsomaniinfenox** [OneSignal/OneSignal-Unity-SDK#631] opened 2023-08-24 11:26 UTC
### What happened?

When I import the latest version 5.0.1, the build is not generating. I am attaching the error report in text files.
Before Importing, I could generate the build, so a Unity build error occurs when using the latest version of one signal SDK.

[CommandInvokationFailure Gradle build failed.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/12428866/CommandInvokationFailure.Gradle.build.failed.txt)
[Picked Up Java Tool Options.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/12428867/Picked.Up.Java.Tool.Options.txt)
[Starting a gradle demon.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/12428868/Starting.a.gradle.demon.txt),

### Steps to reproduce?

```Markdown
In my project, I am using below SDK,
1. Firebase Analytics & Crashlytics SDK
2. Google SignIn
3. Facebook SDK
4. Ironsource Mediation (Admob, Applovin & UnityAds Adapters)
5. com.google.play.review-1.8.1 SDK
```

### What did you expect to happen?

Build should be generated when using the latest SDK.

### Unity version

2021.3.24f1

### OneSignal Unity SDK version

5.0.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment] 2023-08-29 22:19
Closing because this looks to be a duplicate of https://github.com/OneSignal/OneSignal-Unity-SDK/issues/632

**Closed by shepherd-l** 2023-08-29 22:19 UTC
Labels: Duplicate
