### ISSUE TITLE
Still got infocus Notification after set OneSignal.OSInFocusDisplayOption.None;

### ISSUE THREAD

**Issue by kaninhot004** [OneSignal/OneSignal-Unity-SDK#48] opened 2017-06-06 07:19 UTC
# OneSignal v.2.3.0

```
void Start()
{
	extraMessage = null;
	OneSignal.StartInit("APP ID")
	.HandleNotificationOpened(HandleNotificationOpened)
	.HandleNotificationReceived(HandleNotificationReceived)
	.EndInit();
}

public void SetNotification()
{
	if (PlayerPrefs.GetInt("savedOSNotification") == 0)
	{
		PlayerPrefs.SetInt("savedOSNotification", 1);
		OneSignal.inFocusDisplayType = OneSignal.OSInFocusDisplayOption.None;
	}
	else
	{
		PlayerPrefs.SetInt("savedOSNotification", 0);
		OneSignal.inFocusDisplayType = OneSignal.OSInFocusDisplayOption.Notification;
	}
	PlayerPrefs.Save();
}
```

Thank you a lot!

**Comment by jkasten2** [comment] 2017-06-08 01:47
@kaninhot004 Is your `SetNotification` being called after `OneSignal.EndInit`? Also note you must set `OneSignal.inFocusDisplayType` each time your app is started otherwise it defaults to alert.

**Comment by kaninhot004** [comment] 2017-06-08 05:24
I will try it. Thanks for reply sir!

**Comment by mdimello** [comment] 2018-01-18 13:52
I'm using OneSignal Unity SDK v2.5.0 and still got the same problem.

Here's my code:
```
OneSignal.StartInit(ONESIGNAL_APP_ID)
    .Settings(new Dictionary<string, bool>() {
            { OneSignal.kOSSettingsAutoPrompt, false } })
    .EndInit();

OneSignal.inFocusDisplayType = OneSignal.OSInFocusDisplayOption.None;
```

Is there any solution?

**Comment by Nightsd01** [comment] 2018-03-23 00:19
This was caused by the same issue as #43, marking as duplicate.

**Closed by Nightsd01** 2018-03-23 00:19 UTC
