### ISSUE TITLE
In release 2.7.5 onesignalconfig folder is missing

### ISSUE THREAD

**Issue by simar88** [OneSignal/OneSignal-Unity-SDK#142] opened 2018-08-28 12:52 UTC
Please upload and update the latest archive. I solved downloading the previous version of te package and adding to Unity only the folder missing.
Thanks in advance,
Simone

**Comment by jkasten2** [comment] 2018-08-28 22:10
@simar88 Thanks for reporting, the size is definitely much smaller on this release so we will double check to make sure nothing else is missing and get a new release out soon.

**Comment by chall3ng3r** [comment] 2018-09-13 16:41
Still not fixed.

**Comment by jkasten2** [comment] 2018-09-19 03:08
@simar88 @chall3ng3r Sorry for the delay on this. The issue is now fixed in the [2.7.6 Release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.7.6). Thanks

**Closed by jkasten2** 2018-09-19 03:08 UTC
