### ISSUE TITLE
Builds fail with xcode beta for iOS 12

### ISSUE THREAD

**Issue by epsmarkh** [OneSignal/OneSignal-Unity-SDK#131] opened 2018-07-09 06:35 UTC
**Description:**

When trying to build for iOS 12 with the xcode beta, the build fails with the following:

error: Cycle in dependencies between targets 
'OneSignalNotificationServiceExtension' and 'Unity-iPhone'; building 
could produce unreliable results.
Cycle path: OneSignalNotificationServiceExtension → Unity-iPhone → 
OneSignalNotificationServiceExtension
Cycle details:
→ Target 'OneSignalNotificationServiceExtension': CodeSign 
/Users/richardteather/Library/Developer/Xcode/DerivedData/Unity-iPhone-arsiccqnotreagdvswwmpsajjgwt/Build/Products/ReleaseForRunning-iphoneos/OneSignalNotificationServiceExtension.appex
○ That command depends on command in Target 'Unity-iPhone': script 
phase “Run Script”
→ Target 'Unity-iPhone' has target dependency on Target 
'OneSignalNotificationServiceExtension'
→ Target 'OneSignalNotificationServiceExtension': CodeSign 
/Users/richardteather/Library/Developer/Xcode/DerivedData/Unity-iPhone-arsiccqnotreagdvswwmpsajjgwt/Build/Products/ReleaseForRunning-iphoneos/OneSignalNotificationServiceExtension.appex

**Environment**
Onesignal version 2.4.6
Unity 2018.1.5f1
iOS issue only

**Steps to Reproduce Issue:**
  1. Import the latest OneSignalSDK.unitypackage into an empty project
  2. Attempt to build

**Comment by Nightsd01** [comment] 2018-08-15 19:44
Closing due to no response - I am able to build in the Xcode beta just fine so I would assume it's an issue you've managed to solve. If you are still having this issue please feel free to respond and I'll be happy to reopen the issue and help investigate.

**Comment by epsmarkh** [comment] 2018-09-19 11:13
I didn't see the request for more information but there isn't any. We import the SDK into a new empty project, build and get the error. We don't have any other files than those imported from the onesignal package so no we are not importing it elsewhere in our project.

**Comment by epsmarkh** [comment] 2018-09-20 07:02
This can be worked around by switching xcode to use the old build system as described here:

https://help.apple.com/xcode/mac/current/#/dev396bc94c7

This is however an extra manual step in xcode so no use for continuous integration and automated builds so not suitable to use long term.

We are now using the XCode 10 release and still have the issue.

**Comment by altaf-lsg** [comment] 2018-09-20 11:04
Even we faced the same problem, solved it by following epsmarkh comments.
any solution for the new build system coming up?

**Comment by Wolar** [comment] 2018-09-21 14:45
Same problem here on the production Xcode 10. We are not importing NotificationExtension.h anywhere else in the project, I have just checked that. Is there anything I can provide to help reproduce and fix the issue?

**Comment by theDrGray** [comment] 2018-09-22 17:52
Same here.

**Comment by bhallionOhbibi** [comment] 2018-09-25 16:47
Same issue, looking forward a proper fix solution.

**Comment by aresundnes** [comment] 2018-09-25 18:40
Same here!

**Comment by Nightsd01** [comment] 2018-09-25 23:41
I am unable to reproduce this issue with either a brand new project or our existing OneSignal Unity SDK project

@aresundnes @theDrGray @bhallionOhbibi Can you post the following details to help fix the issue:

In the iOS project, in the `Unity-iPhone` folder (or your project name), post the `Unity-iPhone.entitlemnents` file. Also please post your `OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements` file as well.

It would also help to see your project settings, can you post some screenshots of these areas in Xcode:

<img width="958" alt="screen shot 2018-09-25 at 4 38 13 pm" src="https://user-images.githubusercontent.com/8186991/46049180-d6e05200-c0e1-11e8-9f88-67d4e67170ed.png">

<img width="877" alt="screen shot 2018-09-25 at 4 38 20 pm" src="https://user-images.githubusercontent.com/8186991/46049183-db0c6f80-c0e1-11e8-91ee-1b9ad9c7435e.png">

**Comment by Nightsd01** [comment] 2018-09-25 23:43
Lastly, are all of you using the public Xcode 10 release, or are you using a beta? Do you have your Bundle ID properly configured in Unity?

**Comment by aresundnes** [comment] 2018-09-26 05:31
I'm in the public xcode release and everything works fine if i chose the legacy build system as mentioned by @epsmarkh 

I have no OneSignalNotificationServiceExtension.entitlements file in the project, so that might be the reason?

![image](https://user-images.githubusercontent.com/1391113/46058925-49dade80-c15d-11e8-9993-23f8d787e86b.png)


![image](https://user-images.githubusercontent.com/1391113/46059007-ab9b4880-c15d-11e8-8b23-63763b675149.png)

![image](https://user-images.githubusercontent.com/1391113/46059123-3419e900-c15e-11e8-84d8-2ad3ad870d32.png)

**Comment by edencakir** [comment] 2018-09-28 12:16
@epsmarkh thanks for the work around. I guess Onesignal is not yet compatible with Xcode's new build system. @Nightsd01 everything was ok until we update our XCode, and with that workaround, we're able to build our apps without issues.

**Comment by aresundnes** [comment] 2018-10-11 06:57
Still no update on this @Nightsd01 ?

**Comment by jkasten2** [comment] 2018-10-13 03:36
I tried to reproduce this issue on new Unity 2017.4.0f1 project on macOS 10.13.6 with XCode 10.0 (10A255) and it builds without an issue. Test with [OneSignal SDK 2.7.6](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.7.6).

@edencakir @aresundnes @bhallionOhbibi @theDrGray @altaf-lsg are you seeing the exact same error as noted from @epsmarkh [original post](#issue-339321702)?
```
error: Cycle in dependencies between targets
'OneSignalNotificationServiceExtension' and 'Unity-iPhone'; building could produce unreliable results.
Cycle path: OneSignalNotificationServiceExtension → Unity-iPhone → OneSignalNotificationServiceExtension
```

Please check that the `OneSignalNotificationServiceExtension` target has no dependencies like shown below;
![image](https://user-images.githubusercontent.com/645861/46900828-e7bcf180-ce5d-11e8-9903-44d3651c3ce2.png)
I haven't been able to reproduce a case where building would create a "Target Dependencies" entry here but if "Unity-iPhone" was here that would create an error like this. Let us know if this is present for you and if removing it helps.

For anyone reproducing please share a Unity Project and Xcode project reproducing the issue and we can take a look. Thanks!

**Comment by TeemoAtCreate** [comment] 2018-10-29 08:01
@jkasten2 I have the exact same error like the original post. 

I'm using the latest OneSignal SKD 2.7.6, Xcode Version 10.0 (10A255) and Unity 2018.2.13f1. 
The workaround also works for me. ;)

The Target Dependencies you mention are empty, which is correct. 
So I guess it has something to do with the new build system, like @edencakir mentions?

**Comment by acoppes** [comment] 2018-10-29 15:04
> This can be worked around by switching xcode to use the old build system as described here:
> 
> https://help.apple.com/xcode/mac/current/#/dev396bc94c7
> 
> This is however an extra manual step in xcode so no use for continuous integration and automated builds so not suitable to use long term.
> 
> We are now using the XCode 10 release and still have the issue.

I had the same problem and fixed using legacy build system as you mention. Have you tested this solution https://stackoverflow.com/questions/51205221/how-can-i-use-the-legacy-build-system-with-xcode-10s-xcodebuild for automated builds and ci?

**Comment by TeemoAtCreate** [comment] 2018-10-30 07:52
@jkasten2 If I've got any time on my hands, I'll try to see if I can reproduce it with a new project. 
Perhaps it's related to upgrading the projects unity version a couple of times...?

**Comment by nikomikulicic** [comment] 2018-11-14 18:00
I'm having exactly the same issue as posted in original question with Unity 2018.2.14f1 and OneSignal 2.7.7. 

@acoppes 's linked workaround works like charm for automated builds. If you're using fastlane, additional parameters such as `UseModernBuildSystem` can be passed with `xcargs`:

`      
build_app(
        // ... other necessary parameters
        xcargs: "-UseModernBuildSystem=NO"
)
`

**Comment by Wolar** [comment] 2018-11-27 12:33
So I was able to resolve this issue by doing several things (not sure if the last one would help without the other ones).

- Updated CocoaPods (the CocoaPods itself, not resolving the dependencies again)
- Cleaned Xcodes derived data
At this point it still didn't work
- Updated One Signal SDK from 2.7.6 to 2.7.7

**Comment by Wolar** [comment] 2018-11-27 12:57
I take it back, it worked only once (for some strange reason), once I have built it again in Unity and tried to build it again in xcode the issue is back.

**Comment by alex-icesoft** [comment] 2019-01-07 12:04
I've had the same issue with OneSignal and Fabric.
After removing Fabric, xcode managed to build successfully

**Comment by Wolar** [comment] 2019-01-07 13:05
@alex-icesoft I think I have just realised what is wrong by reading your comment. Fabric is adding it's own custom Run Script phase for each target and One Signal is adding it's extension as new target. So it's probably more Fabric issue than OneSignal.

**Comment by alex-icesoft** [comment] 2019-01-07 13:49
Yes, you are right, there are fabric run script attached to each target. Removing the run scripts does resolve the issue, but xcode is crashing every time you click delete next to the run click. After reopen the run script is deleted.

**Comment by Wolar** [comment] 2019-01-07 14:18
The question is if those run script phases should be there. Because if you have more targets, you want to add Fabric to all of them, so either extensions are an exception to that or Fabric should add itself to the targets in a way that is not causing the dependency cycle.

By the way I had the same issue with the Xcode crashing but I was too lazy to workaround / fix it so so far we are using legacy build system.

**Comment by Nightsd01** [comment] 2019-01-07 19:37
@Wolar @alex-icesoft I'm glad we finally figured what was causing the issue! I will keep this issue open a bit longer to see if we can get any more feedback.

Unfortunately there's not much we can do about this other than perhaps adding a warning in our Unity setup guide

**Comment by truonguit2010** [comment] 2019-01-14 10:56
Hi, I meet this problem too.

Cycle in dependencies between targets 'Unity-iPhone' and 'OneSignalNotificationServiceExtension'

How can I fix it now?

**Comment by Wolar** [comment] 2019-01-14 13:05
Manually remove the Run Script phase containing Fabric stuff from the OneSignalNotificationServiceExtension target. Or you can write a script that does that for you. Or use Legacy Xcode build system (file -> workspace settings).

**Comment by Inspekt2** [comment] 2019-01-15 09:14
Have the same issue.
@Wolar "Or you can write a script that does that for you"
Are you talking about changing PBXProject  in OnPostprocessBuild method?

**Comment by wg-mblazin** [comment] 2019-02-04 17:05
I just came across the same issue, did anyone file a bug report with fabric?

**Comment by abkairov** [comment] 2019-04-16 00:36
the same issue here with the OneSignal version 2.7.8, Xcode 10.1

**Comment by rgomezp** [comment] 2019-04-30 20:29
@TeemoAtCreate ,
Were you able to repro in a blank project?

**Comment by rgomezp** [comment] 2019-05-23 20:32
Closing due to no response

**Closed by rgomezp** 2019-05-23 20:32 UTC
Labels: Bug: Not OneSignal, Possible Bug
