### ISSUE TITLE
[iOS] library not found for -liPhone-lib

### ISSUE THREAD

**Issue by ceceomer** [OneSignal/OneSignal-Unity-SDK#237] opened 2019-10-12 14:51 UTC
I got library not found for -liPhone-lib error on Xcode.
Create new unity3d project, use latest AdMob-UnityAds and OneSignal plugins.

When I use only AdMob and unity plugins, it's ok but after OneSignal's, I get error.

Unity 2018.4.11f1 LTS
xCode version: Version 11.1 (11A1027)
macOS Mojave version: 10.14.6 (18G103)
target sdk: 12.0
`ld: library not found for -liPhone-lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by maskedmouse** [comment] 2019-10-14 13:40
I am getting this as well (without admob). We don't use ads but we do use OneSignal. The latest OneSignal SDK is causing this linker error.

Mac OSX Catalina 10.15
Unity 2018.4.10f1
OneSignalSDK v1.9.0
xCode 11.1 (11A1027)

It almost looks like as if the SDK isn't tested for building an app. This is not the first time that builds for iOS break after an SDK update.
Also sidenote Apple changed xcode a bit with signing and entitlements. The documentation for Unity iOS OneSignal setup is out of date.

**Comment by ceceomer** [comment] 2019-10-14 17:11
@maskedmouse I found the problem in here [issue link](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/233#issue-503497319)
but after adding missing library_search_path urls, build success but my app freezes.

**Comment by rgomezp** [comment] 2019-10-22 00:09
Please make sure you have followed our Troubleshooting guide: https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Comment by maskedmouse** [comment] 2019-10-22 05:41
@rgomezp ghis is about iOS builds not android

**Comment by rgomezp** [comment] 2019-10-22 22:28
My apologies, let's continue the discussion on the original thread since this is a duplicate of https://github.com/OneSignal/OneSignal-Unity-SDK/issues/233

**Closed by rgomezp** 2019-10-22 22:28 UTC
Labels: Help Wanted
