### ISSUE TITLE
Lava Devices - java.lang.Error: FATAL EXCEPTION Caused by at android.os.Parcel.readException

### ISSUE THREAD

**Issue by mubshar1** [OneSignal/OneSignal-Unity-SDK#191] opened 2019-05-27 06:31 UTC
**Description:**

 java.lang.Error

com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob

Lava Z60S (Z60s), Android 8.1

java.lang.Error: FATAL EXCEPTION [FocusHandlerThread]
Unity version     : 2018.3.0f2
Device model      : LAVA Z60s
Device fingerprint: LAVA/Z60s/Z60s:8.1.0/O11019/1539786496:user/release-keys
Caused by
  at android.os.Parcel.readException (Parcel.java:2009)
  at android.os.Parcel.readException (Parcel.java:1951)
  at android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:180)
  at android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:44)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob (OneSignalSyncServiceUtils.java:148)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:116)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:63)
  at com.onesignal.OneSignal.onAppLostFocus (OneSignal.java:1096)
  at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run (ActivityLifecycleHandler.java:171)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)

Z60S (Z60s)	          204	46.8%
Z61 (Z61)	                 145	33.3%
Z61-2GB (Z61_2GB)	  58	13.3%
iris88 (iris88)	          13	3.0%
Z91 (Z91)	                   11	2.5%
iris65 (iris65)	            3	0.7%
i7 (TECNO-i7)	             
![Capture](https://user-images.githubusercontent.com/45542019/58400495-a12aa900-8074-11e9-9208-beffbe448a08.PNG)

1	0.2%
Galaxy J2 Core (j2corelte)	1	0.2%

**Comment by rgomezp** [comment] 2019-05-29 16:30
@mubshar1  Thanks for reporting.
Could you provide the details below so we can narrow down the issue?

1. Are you able to reproduce the issue on your devices?
2. How many users is this crash effecting?
3. Have you attempted to contact LAVA directly regarding this issue?

**Comment by rgomezp** [comment] 2019-06-11 21:53
Closing due to no response

**Comment by mubshar1** [comment] 2019-06-12 04:47
> 1. Are you able to reproduce the issue on your devices?
Yes
> 2. How many users is this crash effecting?
Approx 500 daily
> 3. Have you attempted to contact LAVA directly regarding this issue?
it's not only in LAVA, but some other devices also affected.

**Comment by rgomezp** [comment] 2019-06-12 17:45
Hello,
What other devices are seeing the issue? Also, can you please attempt to reproduce on a non-lava device?

**Comment by mubshar1** [comment] 2019-06-17 04:19
yes mainly Samsung J2, iris 88, iris 66 and all lava devices producing this issue.

**Comment by rgomezp** [comment] 2019-06-28 23:06
Hello,
Please reach out through our support channel at onesignal.com with a blank project that reproduces this issue. This will help expedite the process of resolving your issue. Thanks!

**Closed** 2019-07-03 20:25 UTC
Labels: Need More Information, wontfix
