### ISSUE TITLE
Onesignal build not installing in Android 12 (API 31), missing required android:export in AndroidManifest.xml

### ISSUE THREAD

**Issue by RafaelCarpetres** [OneSignal/OneSignal-Unity-SDK#431] opened 2022-01-12 12:23 UTC
I'm having big trouble with Onesignal 2.13.6 Apk's in Android 12.
![image](https://user-images.githubusercontent.com/74305298/149139491-e2a3e002-5e5a-44e8-944a-9590a32fb98c.png)

We are getting this issue when try to install our Apk to any Android 12 device (tried with Samsung S21 pro and Android Emulator API 31), this installation is working fine on any other device (iOS, Android 11 and older)

I updated the OneSignal to the AssetStore version but the issue is still happening

**Comment by frostweep** [comment] 2022-01-13 07:36
Hello,

We facing the same issue and also didnt found a solution yet since the problem is in the compiled library. 

I also know that Unity team did changes in latest Unity version that adds endroid:exported=true during build but I dont think that it will also modify compiled library.

Currently we are looking on using of latest beta version of SDK which should include fix already.

**Comment by RafaQlo** [comment] 2022-01-13 12:16
Yeah, the screenshot build is in Unity 2020.3.25 LTS with the android:exported fixed, so the problem is still OneSignal

**Comment by RafaQlo** [comment] 2022-01-13 17:05
I'm trying to update to OneSignal 3.0.0 - beta.3 but I'm getting a lot of issues related to the new iOS package

![imagen](https://user-images.githubusercontent.com/40049108/149375482-f89ddadf-e375-4c0f-a63c-c3990f48af33.png)

**Comment by jkasten2** [comment] 2022-04-23 20:34
@RafaelCarpetres This compatibility is addressed in the OneSignal-Unity-SDK 3.0.0, see details in https://github.com/OneSignal/OneSignal-Unity-SDK/issues/415 on the steps to migrate to the major version.

@RSJcl Some of the errors, the ones with PBXProjectExtension.cs are fixed in the released 3.0.0 version. The others require you to follow the [migration instructions](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md). Please open a new issue if you continue to see these compile errors after double checking the guide.

Since this issue topic is on a specific Android 12 issue and it is now resolved in a release version closing this issue.

**Closed by jkasten2** 2022-04-23 20:34 UTC
